DEFINE
	FUNCTION Example.Tests = () =>
	UNION (
		PQL.Assert.ShouldNotBeNull("ShouldNotBeNull: DISTINCTCOUNTNOBLANK expression should pass", DISTINCTCOUNTNOBLANK('TestData'[ID])),
		PQL.Assert.Col.ShouldNotBeNull("Col.ShouldNotBeNull: ID has values", 'TestData'[ID]),
		PQL.Assert.Col.ShouldNotBeNull("Col.ShouldNotBeNull: Nullable should have values", 'TestData'[NullableField])
	)

EVALUATE Example.Tests()
